import { MENUS } from './enum'
import type { IPermissions } from './interface'

export const adminPermissions = (): Record<MENUS, IPermissions> => ({
  [MENUS.USER]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ADMIN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PERMISSIONS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.LOGS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLES]: { read: true, edit: false, create: false, delete: false },
  [MENUS.PROJECTS]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDORS]: { read: true, edit: true, create: false, delete: false },
  [MENUS.VENDOR_ASIA]: { read: true, edit: true, create: false, delete: false },
  [MENUS.VENDOR_INDIA]: { read: true, edit: true, create: false, delete: false },
  [MENUS.VENDOR_EUROPE]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_AMERICA]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_TAIWAN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_JAPAN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_GERMANY]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_UK]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_CHAT]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_ODOMETER]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_PIECHART]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_TELEGRAM]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_ADMIN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLE_ROOT]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_USER]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLE_VENDOR]: { read: true, edit: true, create: true, delete: true },
})

export const rootPermissions = (): Record<MENUS, IPermissions> => ({
  [MENUS.USER]: { read: true, edit: true, create: false, delete: false },
  [MENUS.ADMIN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PERMISSIONS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.LOGS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLES]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECTS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDORS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_ASIA]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_INDIA]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_EUROPE]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_AMERICA]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_TAIWAN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_JAPAN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_GERMANY]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_UK]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_CHAT]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_ODOMETER]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_PIECHART]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_TELEGRAM]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLE_ADMIN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLE_ROOT]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLE_USER]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLE_VENDOR]: { read: true, edit: true, create: true, delete: true },
})

export const userPermissions = (): Record<MENUS, IPermissions> => ({
  [MENUS.USER]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ADMIN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PERMISSIONS]: { read: false, edit: false, create: false, delete: false },
  [MENUS.LOGS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLES]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECTS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDORS]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_ASIA]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_INDIA]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_EUROPE]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_AMERICA]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_TAIWAN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_JAPAN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_GERMANY]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDOR_UK]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_CHAT]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_ODOMETER]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_PIECHART]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_TELEGRAM]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLE_ADMIN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_ROOT]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_USER]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_VENDOR]: { read: false, edit: false, create: false, delete: false },
})

export const vendorPermissions = (): Record<MENUS, IPermissions> => ({
  [MENUS.USER]: { read: true, edit: false, create: false, delete: false },
  [MENUS.ADMIN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PERMISSIONS]: { read: false, edit: false, create: false, delete: false },
  [MENUS.LOGS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.ROLES]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECTS]: { read: false, edit: false, create: false, delete: false },
  [MENUS.VENDORS]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_ASIA]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_INDIA]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_EUROPE]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_AMERICA]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_TAIWAN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_JAPAN]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_GERMANY]: { read: true, edit: true, create: true, delete: true },
  [MENUS.VENDOR_UK]: { read: true, edit: true, create: true, delete: true },
  [MENUS.PROJECT_CHAT]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_ODOMETER]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_PIECHART]: { read: false, edit: false, create: false, delete: false },
  [MENUS.PROJECT_TELEGRAM]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_ADMIN]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_ROOT]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_USER]: { read: false, edit: false, create: false, delete: false },
  [MENUS.ROLE_VENDOR]: { read: false, edit: false, create: false, delete: false },
})
